# Generated by Django 5.1.7 on 2025-03-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='header_image_url',
            field=models.URLField(blank=True, help_text='URL for an image to display at the top of the article.', max_length=300, null=True),
        ),
    ]
