# Generated by Django 5.2 on 2025-04-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_author_name_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_name_ar',
            field=models.CharField(blank=True, help_text='Display author name (if not linked to user)', max_length=100, null=True, verbose_name='Author Name'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_name_en',
            field=models.CharField(blank=True, help_text='Display author name (if not linked to user)', max_length=100, null=True, verbose_name='Author Name'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
    ]
