
BBBB BBBBBB
BBBB BBBB

XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
    BB BBBBBBBBBBBBBBBBBBBB
      
      XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'%(game.title)s Cover') SSSSSSSSSSSSSS SSSSSXX
    BBBB
      
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
        XXXXXX gettext(u'No Image') XXXXXXX
      XXXXXX
    BBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXX 

      XX XXXXXXXXXXXXXXXXXX
         BB BBBBBBBBBBBBBBBBBBB 
         BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBB X BBBBB
         BB BBBBBBBBBBBBBBBBBBB 
         BB BBBBBBBBBBBBBBBBB XFFFFFFFFXBBBBB
      XXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
         XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXBBBBXXXXBBBBBXXX
             XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             
             XXXXX XXXXXXXXXXXXXXXXXXXXX
                
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBB
                BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
                BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBB
                BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBB
                BBBB 
                BBBBB
             XXXXXXX
             
         XXXXXXX
         BB BBBBBBBBBBBBBBBBBBBBBBBB
              
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Adjustable') XXXXXXX
         BBBBB
         XXX XXXXXXXXXXXXX
         BBB BBBB BB BBBBBBBBBBBBBB
            
           XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX 
         BBBBBB
      XXXXXX
    XXXXXX
  XXXXXX
XXXX