# Generated by Django 5.1.7 on 2025-03-29 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RatingTier',
            fields=[
                ('tier_code', models.CharField(choices=[('HAL', '✅ Halal / Mubah'), ('MSH', '⚠️ Mashbouh'), ('HRM', '❌ Haram'), ('KSK', '🛑 Kufr / Shirk')], max_length=3, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=50, unique=True)),
                ('color_hex', models.CharField(help_text='Hex color code, e.g., #00FF00', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display tiers (0=first)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly name. Leave blank to auto-generate from title.', max_length=220, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Short description shown in lists.')),
                ('cover_image_url', models.URLField(blank=True, help_text="URL for the game's cover image.", max_length=300, null=True)),
                ('rationale', models.TextField(help_text='Detailed justification for the rating.')),
                ('developer', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('flags', models.ManyToManyField(blank=True, related_name='games', to='ratings.flag')),
                ('rating_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='ratings.ratingtier')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
