# Generated by Django 5.1.7 on 2025-04-06 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_game_original_rating_tier_alter_game_rating_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='audio_music_details',
        ),
        migrations.RemoveField(
            model_name='game',
            name='audio_music_reason',
        ),
        migrations.RemoveField(
            model_name='game',
            name='audio_music_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='immorality_details',
        ),
        migrations.RemoveField(
            model_name='game',
            name='immorality_reason',
        ),
        migrations.RemoveField(
            model_name='game',
            name='immorality_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='substances_gambling_details',
        ),
        migrations.RemoveField(
            model_name='game',
            name='substances_gambling_reason',
        ),
        migrations.RemoveField(
            model_name='game',
            name='substances_gambling_severity',
        ),
        migrations.AlterField(
            model_name='game',
            name='flags',
            field=models.ManyToManyField(blank=True, help_text='Quick visual indicators for potential content types.', related_name='games_with_flag', to='ratings.flag', verbose_name='Content Flags'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating_tier',
            field=models.ForeignKey(help_text='Overall MGC Rating based on detailed assessment (AFTER adjustment, if any).', on_delete=django.db.models.deletion.PROTECT, related_name='games_final_tier', to='ratings.ratingtier', verbose_name='Rating Tier (Final/Achievable)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='requires_adjustment',
            field=models.BooleanField(default=False, help_text='Check if this game needs user adjustments (settings, mods) to meet its assigned final rating tier.', verbose_name='Requires Adjustment'),
        ),
    ]
