# Generated by Django 5.1.7 on 2025-03-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_game_description_image_url_game_is_adjustable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ratingtier',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='description_image_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_adjustable',
        ),
        migrations.AddField(
            model_name='game',
            name='has_spoilers_in_details',
            field=models.BooleanField(default=False, help_text='Check this if any detail sections contain potential plot spoilers.'),
        ),
        migrations.AddField(
            model_name='game',
            name='requires_adjustment',
            field=models.BooleanField(default=False, help_text='Check if this game needs user adjustments (settings, mods) to meet its assigned Halal/Mubah rating.'),
        ),
        migrations.AddField(
            model_name='ratingtier',
            name='symbol',
            field=models.CharField(default='?', max_length=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='aqidah_details',
            field=models.TextField(blank=True, help_text='Specific examples related to Aqidah concerns (magic, deities, ideologies etc).'),
        ),
        migrations.AlterField(
            model_name='game',
            name='audio_music_details',
            field=models.TextField(blank=True, help_text='Details about background music, lyrics, ability to mute.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text="URL for the game's cover image.", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='immorality_details',
            field=models.TextField(blank=True, help_text="Examples of 'Awrah, suggestive themes, promotion of impermissible relationships, bad language/conduct."),
        ),
        migrations.AlterField(
            model_name='game',
            name='online_conduct_details',
            field=models.TextField(blank=True, help_text='Risks related to online chat, community toxicity, moderation.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rationale',
            field=models.TextField(blank=True, help_text='General rationale summary (optional).'),
        ),
        migrations.AlterField(
            model_name='game',
            name='substances_gambling_details',
            field=models.TextField(blank=True, help_text='Examples of substance use/promotion, gambling mechanics.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_addiction_details',
            field=models.TextField(blank=True, help_text='Notes on addictive mechanics, time investment required, potential for neglecting duties.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='violence_details',
            field=models.TextField(blank=True, help_text='Specific examples of violence, gore, context.'),
        ),
        migrations.AlterField(
            model_name='ratingtier',
            name='tier_code',
            field=models.CharField(choices=[('HAL', 'Halal / Mubah'), ('MSH', 'Mashbouh'), ('HRM', 'Haram'), ('KSK', 'Kufr / Shirk')], max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
