# Generated by Django 5.1.7 on 2025-04-10 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_remove_game_audio_music_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='adjustable_flags',
        ),
        migrations.RemoveField(
            model_name='game',
            name='adjustment_guide',
        ),
        migrations.RemoveField(
            model_name='game',
            name='adjustment_guide_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='adjustment_guide_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='aqidah_details',
        ),
        migrations.RemoveField(
            model_name='game',
            name='aqidah_details_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='aqidah_details_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='aqidah_reason',
        ),
        migrations.RemoveField(
            model_name='game',
            name='aqidah_reason_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='aqidah_reason_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='aqidah_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='haram_depictions_details',
        ),
        migrations.RemoveField(
            model_name='game',
            name='haram_depictions_details_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='haram_depictions_details_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='haram_depictions_reason',
        ),
        migrations.RemoveField(
            model_name='game',
            name='haram_depictions_reason_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='haram_depictions_reason_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='haram_depictions_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='normalization_haram_details',
        ),
        migrations.RemoveField(
            model_name='game',
            name='normalization_haram_details_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='normalization_haram_details_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='normalization_haram_reason',
        ),
        migrations.RemoveField(
            model_name='game',
            name='normalization_haram_reason_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='normalization_haram_reason_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='normalization_haram_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='online_conduct_details',
        ),
        migrations.RemoveField(
            model_name='game',
            name='online_conduct_details_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='online_conduct_details_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='online_conduct_reason',
        ),
        migrations.RemoveField(
            model_name='game',
            name='online_conduct_reason_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='online_conduct_reason_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='online_conduct_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='original_rating_tier',
        ),
        migrations.RemoveField(
            model_name='game',
            name='requires_adjustment',
        ),
        migrations.RemoveField(
            model_name='game',
            name='simulation_haram_details',
        ),
        migrations.RemoveField(
            model_name='game',
            name='simulation_haram_details_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='simulation_haram_details_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='simulation_haram_reason',
        ),
        migrations.RemoveField(
            model_name='game',
            name='simulation_haram_reason_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='simulation_haram_reason_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='simulation_haram_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time_addiction_details',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time_addiction_details_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time_addiction_details_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time_addiction_reason',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time_addiction_reason_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time_addiction_reason_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time_addiction_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='violence_details',
        ),
        migrations.RemoveField(
            model_name='game',
            name='violence_details_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='violence_details_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='violence_reason',
        ),
        migrations.RemoveField(
            model_name='game',
            name='violence_reason_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='violence_reason_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='violence_severity',
        ),
        migrations.AddField(
            model_name='game',
            name='contradictory_ideologies_details',
            field=models.TextField(blank=True, verbose_name='6. Contradictory Ideologies Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='contradictory_ideologies_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='6. Contradictory Ideologies Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='contradictory_ideologies_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='6. Contradictory Ideologies Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='contradictory_ideologies_reason',
            field=models.TextField(blank=True, verbose_name='6. Contradictory Ideologies Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='contradictory_ideologies_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='6. Contradictory Ideologies Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='contradictory_ideologies_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='6. Contradictory Ideologies Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='contradictory_ideologies_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='6. Contradictory Ideologies Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='depict_unseen_details',
            field=models.TextField(blank=True, verbose_name='4. Depict Unseen Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='depict_unseen_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='4. Depict Unseen Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='depict_unseen_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='4. Depict Unseen Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='depict_unseen_reason',
            field=models.TextField(blank=True, verbose_name='4. Depict Unseen Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='depict_unseen_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='4. Depict Unseen Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='depict_unseen_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='4. Depict Unseen Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='depict_unseen_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='4. Depict Unseen Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='financial_extravagance_details',
            field=models.TextField(blank=True, verbose_name='17. Financial Extravagance Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='financial_extravagance_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='17. Financial Extravagance Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='financial_extravagance_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='17. Financial Extravagance Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='financial_extravagance_reason',
            field=models.TextField(blank=True, verbose_name='17. Financial Extravagance Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='financial_extravagance_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='17. Financial Extravagance Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='financial_extravagance_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='17. Financial Extravagance Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='financial_extravagance_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='17. Financial Extravagance Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='forced_shirk_details',
            field=models.TextField(blank=True, verbose_name='1. Forced Shirk Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='forced_shirk_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='1. Forced Shirk Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='forced_shirk_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='1. Forced Shirk Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='forced_shirk_reason',
            field=models.TextField(blank=True, verbose_name='1. Forced Shirk Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='forced_shirk_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='1. Forced Shirk Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='forced_shirk_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='1. Forced Shirk Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='forced_shirk_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='1. Forced Shirk Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='gambling_details',
            field=models.TextField(blank=True, verbose_name='9. Gambling/Maysir Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='gambling_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='9. Gambling/Maysir Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='gambling_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='9. Gambling/Maysir Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='gambling_reason',
            field=models.TextField(blank=True, verbose_name='9. Gambling/Maysir Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='gambling_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='9. Gambling/Maysir Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='gambling_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='9. Gambling/Maysir Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='gambling_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='9. Gambling/Maysir Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='insult_islam_details',
            field=models.TextField(blank=True, verbose_name='3. Insult Islam Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='insult_islam_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='3. Insult Islam Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='insult_islam_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='3. Insult Islam Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='insult_islam_reason',
            field=models.TextField(blank=True, verbose_name='3. Insult Islam Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='insult_islam_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='3. Insult Islam Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='insult_islam_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='3. Insult Islam Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='insult_islam_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='3. Insult Islam Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='lying_details',
            field=models.TextField(blank=True, verbose_name='10. Lying (Player) Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='lying_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='10. Lying (Player) Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='lying_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='10. Lying (Player) Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='lying_reason',
            field=models.TextField(blank=True, verbose_name='10. Lying (Player) Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='lying_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='10. Lying (Player) Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='lying_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='10. Lying (Player) Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='lying_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='10. Lying (Player) Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='magic_sorcery_details',
            field=models.TextField(blank=True, verbose_name='5. Magic/Sorcery Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='magic_sorcery_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='5. Magic/Sorcery Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='magic_sorcery_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='5. Magic/Sorcery Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='magic_sorcery_reason',
            field=models.TextField(blank=True, verbose_name='5. Magic/Sorcery Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='magic_sorcery_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='5. Magic/Sorcery Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='magic_sorcery_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='5. Magic/Sorcery Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='magic_sorcery_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='5. Magic/Sorcery Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='music_instruments_details',
            field=models.TextField(blank=True, verbose_name='8. Music/Instruments Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='music_instruments_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='8. Music/Instruments Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='music_instruments_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='8. Music/Instruments Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='music_instruments_reason',
            field=models.TextField(blank=True, verbose_name='8. Music/Instruments Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='music_instruments_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='8. Music/Instruments Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='music_instruments_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='8. Music/Instruments Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='music_instruments_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='8. Music/Instruments Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_haram_rels_details',
            field=models.TextField(blank=True, verbose_name='13. Normalize Haram Relationships Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_haram_rels_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='13. Normalize Haram Relationships Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_haram_rels_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='13. Normalize Haram Relationships Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_haram_rels_reason',
            field=models.TextField(blank=True, verbose_name='13. Normalize Haram Relationships Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_haram_rels_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='13. Normalize Haram Relationships Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_haram_rels_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='13. Normalize Haram Relationships Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_haram_rels_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='13. Normalize Haram Relationships Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_substances_details',
            field=models.TextField(blank=True, verbose_name='14. Normalize Substances Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_substances_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='14. Normalize Substances Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_substances_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='14. Normalize Substances Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_substances_reason',
            field=models.TextField(blank=True, verbose_name='14. Normalize Substances Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_substances_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='14. Normalize Substances Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_substances_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='14. Normalize Substances Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='normalize_substances_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='14. Normalize Substances Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='nudity_lewdness_details',
            field=models.TextField(blank=True, verbose_name='7. Nudity/Lewdness Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='nudity_lewdness_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='7. Nudity/Lewdness Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='nudity_lewdness_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='7. Nudity/Lewdness Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='nudity_lewdness_reason',
            field=models.TextField(blank=True, verbose_name='7. Nudity/Lewdness Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='nudity_lewdness_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='7. Nudity/Lewdness Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='nudity_lewdness_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='7. Nudity/Lewdness Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='nudity_lewdness_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='7. Nudity/Lewdness Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_communication_details',
            field=models.TextField(blank=True, verbose_name='18. Online Communication Risks Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_communication_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='18. Online Communication Risks Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_communication_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='18. Online Communication Risks Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_communication_reason',
            field=models.TextField(blank=True, verbose_name='18. Online Communication Risks Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_communication_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='18. Online Communication Risks Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_communication_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='18. Online Communication Risks Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_communication_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='18. Online Communication Risks Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='profanity_obscenity_details',
            field=models.TextField(blank=True, verbose_name='15. Profanity/Obscenity Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='profanity_obscenity_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='15. Profanity/Obscenity Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='profanity_obscenity_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='15. Profanity/Obscenity Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='profanity_obscenity_reason',
            field=models.TextField(blank=True, verbose_name='15. Profanity/Obscenity Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='profanity_obscenity_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='15. Profanity/Obscenity Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='profanity_obscenity_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='15. Profanity/Obscenity Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='profanity_obscenity_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='15. Profanity/Obscenity Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='promote_shirk_details',
            field=models.TextField(blank=True, verbose_name='2. Promote Shirk/Kufr Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='promote_shirk_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='2. Promote Shirk/Kufr Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='promote_shirk_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='2. Promote Shirk/Kufr Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='promote_shirk_reason',
            field=models.TextField(blank=True, verbose_name='2. Promote Shirk/Kufr Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='promote_shirk_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='2. Promote Shirk/Kufr Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='promote_shirk_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='2. Promote Shirk/Kufr Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='promote_shirk_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='2. Promote Shirk/Kufr Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_killing_details',
            field=models.TextField(blank=True, verbose_name='11. Simulate Killing/Aggression Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_killing_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='11. Simulate Killing/Aggression Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_killing_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='11. Simulate Killing/Aggression Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_killing_reason',
            field=models.TextField(blank=True, verbose_name='11. Simulate Killing/Aggression Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_killing_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='11. Simulate Killing/Aggression Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_killing_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='11. Simulate Killing/Aggression Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_killing_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='11. Simulate Killing/Aggression Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_theft_crime_details',
            field=models.TextField(blank=True, verbose_name='12. Simulate Theft/Crime Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_theft_crime_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='12. Simulate Theft/Crime Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_theft_crime_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='12. Simulate Theft/Crime Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_theft_crime_reason',
            field=models.TextField(blank=True, verbose_name='12. Simulate Theft/Crime Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_theft_crime_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='12. Simulate Theft/Crime Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_theft_crime_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='12. Simulate Theft/Crime Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='simulate_theft_crime_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='12. Simulate Theft/Crime Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_wasting_details',
            field=models.TextField(blank=True, verbose_name='16. Excessive Time Wasting Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_wasting_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='16. Excessive Time Wasting Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_wasting_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='16. Excessive Time Wasting Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_wasting_reason',
            field=models.TextField(blank=True, verbose_name='16. Excessive Time Wasting Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_wasting_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='16. Excessive Time Wasting Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_wasting_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='16. Excessive Time Wasting Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_wasting_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='16. Excessive Time Wasting Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='ugc_risks_details',
            field=models.TextField(blank=True, verbose_name='19. User Generated Content Risks Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='ugc_risks_details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='19. User Generated Content Risks Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='ugc_risks_details_en',
            field=models.TextField(blank=True, null=True, verbose_name='19. User Generated Content Risks Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='ugc_risks_reason',
            field=models.TextField(blank=True, verbose_name='19. User Generated Content Risks Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='ugc_risks_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='19. User Generated Content Risks Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='ugc_risks_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='19. User Generated Content Risks Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='ugc_risks_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Severe')], default='N', max_length=1, verbose_name='19. User Generated Content Risks Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='flags',
            field=models.ManyToManyField(blank=True, help_text='Quick visual indicators for major concerns (use sparingly).', related_name='games_with_flag', to='ratings.flag', verbose_name='Content Flags'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating_tier',
            field=models.ForeignKey(help_text='Overall MGC Rating calculated based on detailed assessment.', on_delete=django.db.models.deletion.PROTECT, related_name='games_final_tier', to='ratings.ratingtier', verbose_name='Overall Rating Tier'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rationale',
            field=models.TextField(blank=True, help_text='Overall reasoning summary for the final rating.', verbose_name='Overall Rationale'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rationale_ar',
            field=models.TextField(blank=True, help_text='Overall reasoning summary for the final rating.', null=True, verbose_name='Overall Rationale'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rationale_en',
            field=models.TextField(blank=True, help_text='Overall reasoning summary for the final rating.', null=True, verbose_name='Overall Rationale'),
        ),
        migrations.AlterField(
            model_name='ratingtier',
            name='tier_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
