# Generated by Django 5.1.7 on 2025-04-10 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_remove_game_adjustable_flags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flag',
            options={'ordering': ['symbol'], 'verbose_name': 'Content Flag', 'verbose_name_plural': 'Content Flags'},
        ),
        migrations.AlterField(
            model_name='flag',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='description_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='description_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='symbol',
            field=models.CharField(max_length=100, unique=True, verbose_name='Symbol (Identifier)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='contradictory_ideologies_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='6. Contradictory Ideologies Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='depict_unseen_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='4. Depict Unseen Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='financial_extravagance_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='17. Financial Extravagance Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='flags',
            field=models.ManyToManyField(blank=True, help_text='Flags automatically assigned based on detailed severity ratings.', related_name='games_flagged', to='ratings.flag', verbose_name='Content Flags (Auto-assigned)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='forced_shirk_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='1. Forced Shirk Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gambling_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='9. Gambling/Maysir Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='insult_islam_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='3. Insult Islam Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='lying_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='10. Lying (Player) Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='magic_sorcery_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='5. Magic/Sorcery Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='music_instruments_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='8. Music/Instruments Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='normalize_haram_rels_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='13. Normalize Haram Relationships Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='normalize_substances_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='14. Normalize Substances Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='nudity_lewdness_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='7. Nudity/Lewdness Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='online_communication_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='18. Online Communication Risks Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='profanity_obscenity_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='15. Profanity/Obscenity Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='promote_shirk_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='2. Promote Shirk/Kufr Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating_tier',
            field=models.ForeignKey(help_text='Overall MGC Rating calculated based on detailed assessment.', on_delete=django.db.models.deletion.PROTECT, related_name='games_rated', to='ratings.ratingtier', verbose_name='Overall Rating Tier'),
        ),
        migrations.AlterField(
            model_name='game',
            name='simulate_killing_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='11. Simulate Killing/Aggression Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='simulate_theft_crime_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='12. Simulate Theft/Crime Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_wasting_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='16. Excessive Time Wasting Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='ugc_risks_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='19. User Generated Content Risks Severity'),
        ),
    ]
