# Generated by Django 5.1.7 on 2025-03-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_alter_flag_options_alter_ratingtier_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingtier',
            name='symbol',
        ),
        migrations.AddField(
            model_name='ratingtier',
            name='icon_name',
            field=models.CharField(default='help', help_text='Material Symbols icon name (e.g., check_circle, warning, cancel, gpp_bad). See fonts.google.com/icons', max_length=50),
        ),
    ]
