# Generated by Django 5.1.7 on 2025-04-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_alter_flag_options_alter_flag_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingtier',
            name='color_hex',
            field=models.CharField(help_text='Hex color code', max_length=7, verbose_name='Color Hex'),
        ),
        migrations.AlterField(
            model_name='ratingtier',
            name='icon_name',
            field=models.CharField(default='help', help_text='Material Symbols icon name', max_length=50, verbose_name='Icon Name'),
        ),
        migrations.AlterField(
            model_name='ratingtier',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display Order', verbose_name='Display Order'),
        ),
    ]
