# Generated by Django 5.1.7 on 2025-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_remove_ratingtier_symbol_ratingtier_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='aqidah_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference (e.g., specific principle, Fatwa summary) for the Aqidah severity rating.'),
        ),
        migrations.AddField(
            model_name='game',
            name='audio_music_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Audio/Music severity rating.'),
        ),
        migrations.AddField(
            model_name='game',
            name='immorality_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Immorality severity rating.'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_conduct_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Online Conduct severity rating.'),
        ),
        migrations.AddField(
            model_name='game',
            name='substances_gambling_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Substances/Gambling severity rating.'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_addiction_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Time/Addiction severity rating.'),
        ),
        migrations.AddField(
            model_name='game',
            name='violence_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Violence severity rating.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='has_spoilers_in_details',
            field=models.BooleanField(default=False, help_text="Check this to enable the 'Show/Hide Details' toggle for categories containing potential spoilers."),
        ),
    ]
