# Generated by Django 5.1.7 on 2025-03-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_game_aqidah_reason_game_audio_music_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='adjustment_guide',
            field=models.TextField(blank=True, help_text='Instructions or links on how to adjust settings/mods for Halal/Mashbouh games.'),
        ),
        migrations.AddField(
            model_name='game',
            name='developer_slug',
            field=models.SlugField(blank=True, help_text='Auto-generated slug for developer filtering.', max_length=110),
        ),
        migrations.AddField(
            model_name='game',
            name='epic_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Epic Games Store URL'),
        ),
        migrations.AddField(
            model_name='game',
            name='gog_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='GOG Store URL'),
        ),
        migrations.AddField(
            model_name='game',
            name='other_store_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Other Store URL'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher_slug',
            field=models.SlugField(blank=True, help_text='Auto-generated slug for publisher filtering.', max_length=110),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Steam Store URL'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='audio_music_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='audio_music_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='immorality_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='immorality_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='online_conduct_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='online_conduct_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='substances_gambling_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='substances_gambling_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_addiction_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_addiction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='violence_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='violence_reason',
            field=models.TextField(blank=True),
        ),
    ]
