# Generated by Django 5.1.7 on 2025-04-10 22:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_whymgcpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_score', models.PositiveSmallIntegerField(blank=True, help_text='Optional: Rate the game from 1 (worst) to 5 (best)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='User Rating (1-5)')),
                ('content', models.TextField(blank=True, help_text='Share your detailed perspective or specific concerns.', verbose_name='Review / Detailed Comment')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('moderator_attention_needed', models.BooleanField(default=False, verbose_name='Needs Attention')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('flagged_by', models.ManyToManyField(blank=True, related_name='flagged_contributions', to=settings.AUTH_USER_MODEL, verbose_name='Flagged By')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contributions', to='ratings.game', verbose_name='Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_contributions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Contribution',
                'verbose_name_plural': 'User Contributions',
                'ordering': ['-created_date'],
                'unique_together': {('game', 'user')},
            },
        ),
    ]
