# Generated by Django 5.1.7 on 2025-03-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_game_adjustment_guide_game_developer_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(help_text='e.g., IGN, GameSpot, Metacritic', max_length=100)),
                ('score', models.CharField(blank=True, help_text='e.g., 9/10, 85/100, Recommended', max_length=20)),
                ('review_url', models.URLField(help_text='Direct link to the review', max_length=300, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Optional short quote or summary from the review')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['reviewer_name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='critic_reviews',
            field=models.ManyToManyField(blank=True, help_text='Select critic reviews relevant to this game.', related_name='games', to='ratings.criticreview'),
        ),
    ]
