# Generated by Django 5.1.7 on 2025-04-11 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_usercontribution'), # Replace with your actual previous migration
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- Delete existing contributions to avoid NOT NULL issues ---
        migrations.RunSQL(
            "DELETE FROM ratings_usercontribution;",
            reverse_sql=migrations.RunSQL.noop # No reverse action needed
        ),

        # --- Remove the old field ---
        migrations.RemoveField(
            model_name='usercontribution',
            name='rating_score',
        ),

        # --- Add the new ForeignKey category field (non-nullable) ---
        migrations.AddField(
            model_name='usercontribution',
            name='category',
            field=models.ForeignKey(
                # No default needed as we deleted old rows
                # No null=True needed
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_contributions',
                to='ratings.flag',
                verbose_name='Content Category'
                # preserve_default=False, # Should be false implicitly
            ),
            # Add this line manually if makemigrations didn't include it,
            # but since we deleted rows, it should work without preserve_default=False
            # It tells Django it's okay that we didn't provide a default because the table should be empty.
             preserve_default=False,
        ),

        # --- Add other new fields ---
        migrations.AddField(
            model_name='usercontribution',
            name='is_spoiler',
            field=models.BooleanField(default=False, verbose_name='Contains Spoilers?'),
        ),
        migrations.AddField(
            model_name='usercontribution',
            name='severity_rating',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], max_length=1, null=True, verbose_name='User Severity Rating'),
        ),

        # --- Alter existing fields (keep these as they were) ---
         migrations.AlterField(
            model_name='game',
            name='rationale',
            field=models.TextField(blank=True, help_text='Overall reasoning summary for the final rating.', verbose_name='Rating Summary'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rationale_ar',
            field=models.TextField(blank=True, help_text='Overall reasoning summary for the final rating.', null=True, verbose_name='Rating Summary'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rationale_en',
            field=models.TextField(blank=True, help_text='Overall reasoning summary for the final rating.', null=True, verbose_name='Rating Summary'),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='content',
            field=models.TextField(blank=True, help_text='Explain your rating for this specific category (e.g., where it occurs, context).', verbose_name='Details / Justification'),
        ),

        # --- Alter Model Options (keep this) ---
         migrations.AlterModelOptions(
            name='usercontribution',
            options={'ordering': ['category__description', '-created_date'], 'verbose_name': 'User Contribution (Category)', 'verbose_name_plural': 'User Contributions (Category)'},
        ),

        # --- Ensure AlterUniqueTogether is NOT in this file ---
        # migrations.AlterUniqueTogether(
        #    name='usercontribution',
        #    unique_together={('game', 'user', 'category')},
        # ),
    ]