# Generated by Django 5.1.7 on 2025-03-30 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_criticreview_game_critic_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criticreview',
            options={'ordering': ['reviewer_name'], 'verbose_name': 'Critic Review', 'verbose_name_plural': 'Critic Reviews'},
        ),
        migrations.AlterModelOptions(
            name='flag',
            options={'verbose_name': 'Content Flag', 'verbose_name_plural': 'Content Flags'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date_added'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='ratingtier',
            options={'ordering': ['order'], 'verbose_name': 'Rating Tier', 'verbose_name_plural': 'Rating Tiers'},
        ),
        migrations.AlterField(
            model_name='criticreview',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='criticreview',
            name='review_url',
            field=models.URLField(help_text='Direct link to the review', max_length=300, unique=True, verbose_name='Review URL'),
        ),
        migrations.AlterField(
            model_name='criticreview',
            name='reviewer_name',
            field=models.CharField(help_text='e.g., IGN, GameSpot, Metacritic', max_length=100, verbose_name='Reviewer Name'),
        ),
        migrations.AlterField(
            model_name='criticreview',
            name='score',
            field=models.CharField(blank=True, help_text='e.g., 9/10, 85/100, Recommended', max_length=20, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='criticreview',
            name='summary',
            field=models.TextField(blank=True, help_text='Optional short quote or summary from the review', verbose_name='Summary Quote'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='symbol',
            field=models.CharField(max_length=50, unique=True, verbose_name='Symbol (Icon Name)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='adjustment_guide',
            field=models.TextField(blank=True, help_text='Instructions or links on how to adjust settings/mods for Halal/Mashbouh games.', verbose_name='Adjustment Guide'),
        ),
        migrations.AlterField(
            model_name='game',
            name='aqidah_details',
            field=models.TextField(blank=True, help_text='Specific examples related to Aqidah concerns (magic, deities, ideologies etc).', verbose_name='Aqidah Details'),
        ),
        migrations.AlterField(
            model_name='game',
            name='aqidah_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Aqidah severity rating.', verbose_name='Aqidah Reason'),
        ),
        migrations.AlterField(
            model_name='game',
            name='aqidah_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Prohibited')], default='N', max_length=1, verbose_name='Aqidah Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='audio_music_details',
            field=models.TextField(blank=True, help_text='Details about background music, lyrics, ability to mute.', verbose_name='Audio/Music Details'),
        ),
        migrations.AlterField(
            model_name='game',
            name='audio_music_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Audio/Music severity rating.', verbose_name='Audio/Music Reason'),
        ),
        migrations.AlterField(
            model_name='game',
            name='audio_music_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Prohibited')], default='N', max_length=1, verbose_name='Audio/Music Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text="URL for the game's cover image.", max_length=300, null=True, verbose_name='Cover Image URL'),
        ),
        migrations.AlterField(
            model_name='game',
            name='critic_reviews',
            field=models.ManyToManyField(blank=True, help_text='Select critic reviews relevant to this game.', related_name='games', to='ratings.criticreview', verbose_name='Critic Reviews'),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='flags',
            field=models.ManyToManyField(blank=True, help_text='Quick visual indicators for potential content types.', related_name='games', to='ratings.flag', verbose_name='Content Flags'),
        ),
        migrations.AlterField(
            model_name='game',
            name='has_spoilers_in_details',
            field=models.BooleanField(default=False, help_text="Check this to enable the 'Show/Hide Details' toggle for categories containing potential spoilers.", verbose_name='Has Spoilers in Details'),
        ),
        migrations.AlterField(
            model_name='game',
            name='immorality_details',
            field=models.TextField(blank=True, help_text="Examples of 'Awrah, suggestive themes, promotion of impermissible relationships, bad language/conduct.", verbose_name='Immorality Details'),
        ),
        migrations.AlterField(
            model_name='game',
            name='immorality_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Immorality severity rating.', verbose_name='Immorality Reason'),
        ),
        migrations.AlterField(
            model_name='game',
            name='immorality_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Prohibited')], default='N', max_length=1, verbose_name='Immorality Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='online_conduct_details',
            field=models.TextField(blank=True, help_text='Risks related to online chat, community toxicity, moderation.', verbose_name='Online Conduct Details'),
        ),
        migrations.AlterField(
            model_name='game',
            name='online_conduct_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Online Conduct severity rating.', verbose_name='Online Conduct Reason'),
        ),
        migrations.AlterField(
            model_name='game',
            name='online_conduct_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Prohibited')], default='N', max_length=1, verbose_name='Online Conduct Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating_tier',
            field=models.ForeignKey(help_text='Overall MGC Rating based on detailed assessment.', on_delete=django.db.models.deletion.PROTECT, related_name='games', to='ratings.ratingtier', verbose_name='Rating Tier'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rationale',
            field=models.TextField(blank=True, help_text='General rationale summary (optional).', verbose_name='General Rationale'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='requires_adjustment',
            field=models.BooleanField(default=False, help_text='Check if this game needs user adjustments (settings, mods) to meet its assigned Halal/Mubah rating.', verbose_name='Requires Adjustment'),
        ),
        migrations.AlterField(
            model_name='game',
            name='substances_gambling_details',
            field=models.TextField(blank=True, help_text='Examples of substance use/promotion, gambling mechanics.', verbose_name='Substances/Gambling Details'),
        ),
        migrations.AlterField(
            model_name='game',
            name='substances_gambling_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Substances/Gambling severity rating.', verbose_name='Substances/Gambling Reason'),
        ),
        migrations.AlterField(
            model_name='game',
            name='substances_gambling_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Prohibited')], default='N', max_length=1, verbose_name='Substances/Gambling Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, help_text='Short description shown in lists.', verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_addiction_details',
            field=models.TextField(blank=True, help_text='Notes on addictive mechanics, time investment required, potential for neglecting duties.', verbose_name='Time/Addiction Details'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_addiction_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Time/Addiction severity rating.', verbose_name='Time/Addiction Reason'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_addiction_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Prohibited')], default='N', max_length=1, verbose_name='Time/Addiction Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='game',
            name='violence_details',
            field=models.TextField(blank=True, help_text='Specific examples of violence, gore, context.', verbose_name='Violence Details'),
        ),
        migrations.AlterField(
            model_name='game',
            name='violence_reason',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Violence severity rating.', verbose_name='Violence Reason'),
        ),
        migrations.AlterField(
            model_name='game',
            name='violence_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('P', 'Prohibited')], default='N', max_length=1, verbose_name='Violence Severity'),
        ),
        migrations.AlterField(
            model_name='ratingtier',
            name='color_hex',
            field=models.CharField(help_text='Hex color code, e.g., #00FF00', max_length=7, verbose_name='Color Hex'),
        ),
        migrations.AlterField(
            model_name='ratingtier',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ratingtier',
            name='display_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='ratingtier',
            name='icon_name',
            field=models.CharField(default='help', help_text='Material Symbols icon name (e.g., check_circle, warning, cancel, gpp_bad). See fonts.google.com/icons', max_length=50, verbose_name='Icon Name'),
        ),
        migrations.AlterField(
            model_name='ratingtier',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order to display tiers (0=first)', verbose_name='Display Order'),
        ),
    ]
