# Generated by Django 5.1.7 on 2025-04-11 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_alter_usercontribution_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercontribution',
            unique_together={('game', 'user', 'category')},
        ),
    ]
