# Generated by Django 5.1.7 on 2025-04-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_alter_criticreview_options_alter_flag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='available_android',
            field=models.BooleanField(default=False, verbose_name='Available on Android'),
        ),
        migrations.AddField(
            model_name='game',
            name='available_ios',
            field=models.BooleanField(default=False, verbose_name='Available on iOS'),
        ),
        migrations.AddField(
            model_name='game',
            name='available_pc',
            field=models.BooleanField(default=False, verbose_name='Available on PC'),
        ),
        migrations.AddField(
            model_name='game',
            name='available_ps4',
            field=models.BooleanField(default=False, verbose_name='Available on PS4'),
        ),
        migrations.AddField(
            model_name='game',
            name='available_ps5',
            field=models.BooleanField(default=False, verbose_name='Available on PS5'),
        ),
        migrations.AddField(
            model_name='game',
            name='available_switch',
            field=models.BooleanField(default=False, verbose_name='Available on Nintendo Switch'),
        ),
        migrations.AddField(
            model_name='game',
            name='available_xbox_one',
            field=models.BooleanField(default=False, verbose_name='Available on Xbox One'),
        ),
        migrations.AddField(
            model_name='game',
            name='available_xbox_series',
            field=models.BooleanField(default=False, verbose_name='Available on Xbox Series X|S'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='ratingtier',
            name='tier_code',
            field=models.CharField(choices=[('HAL', 'Halal'), ('MSH', 'Mashbouh'), ('HRM', 'Haram'), ('KFR', 'Kufr')], max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
