# Generated by Django 5.2 on 2025-04-02 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_gamecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecomment',
            options={'ordering': ['created_date'], 'verbose_name': 'Game Comment', 'verbose_name_plural': 'Game Comments'},
        ),
        migrations.AddField(
            model_name='gamecomment',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_comments', to=settings.AUTH_USER_MODEL, verbose_name='Flagged By'),
        ),
        migrations.AddField(
            model_name='gamecomment',
            name='moderator_attention_needed',
            field=models.BooleanField(default=False, verbose_name='Needs Attention'),
        ),
        migrations.AlterField(
            model_name='gamecomment',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='Approved'),
        ),
    ]
