# Generated by Django 5.1.7 on 2025-04-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_remove_game_contradictory_ideologies_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flag',
            options={'ordering': ['description'], 'verbose_name': 'Content Flag', 'verbose_name_plural': 'Content Flags'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date_updated'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='contradictory_ideologies_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='depict_unseen_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='financial_extravagance_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='forced_shirk_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='has_spoilers_in_details',
        ),
        migrations.RemoveField(
            model_name='game',
            name='insult_islam_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='magic_sorcery_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='normalize_haram_rels_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='normalize_substances_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='nudity_lewdness_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='online_communication_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='profanity_obscenity_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='promote_shirk_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='simulate_killing_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='simulate_theft_crime_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time_wasting_severity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ugc_risks_severity',
        ),
        migrations.RemoveField(
            model_name='usercontribution',
            name='is_spoiler',
        ),
        migrations.AddField(
            model_name='game',
            name='assuming_divinity_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='A3. Assuming Divinity Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='crime_violence_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='C4. Normalizing Crime/Violence Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='despair_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='D2. Despair Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='deviant_ideologies_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='A5. Deviant Ideologies Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='disdain_arrogance_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='C1. Normalizing Disdain/Arrogance Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='distorting_islam_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='A1. Distorting Islam Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='horror_fear_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='D1. Horror/Fear Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='indecency_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='B3. Indecency Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='intoxicants_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='C3. Normalizing Intoxicants Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='magic_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='C2. Normalizing Magic Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_interactions_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='D4. Online Interactions Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='profanity_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='C5. Normalizing Profanity Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='promoting_kufr_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='A2. Promoting Kufr/Shirk Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='spending_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='D3. Spending Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='tampering_ghaib_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='A4. Tampering Ghaib Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_waste_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='B5. Time Waste Severity'),
        ),
        migrations.AddField(
            model_name='game',
            name='user_content_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='D5. User Content Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gambling_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='B1. Gambling Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='lying_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='B2. Lying Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='music_instruments_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='B4. Music/Instruments Severity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating_tier',
            field=models.ForeignKey(blank=True, help_text='Overall MGC Rating calculated based on detailed assessment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_rated', to='ratings.ratingtier', verbose_name='Overall Rating Tier'),
        ),
    ]
