# Generated by Django 5.2 on 2025-04-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_alter_gamecomment_options_gamecomment_flagged_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticreview',
            name='summary_ar',
            field=models.TextField(blank=True, help_text='Optional short quote or summary from the review', null=True, verbose_name='Summary Quote'),
        ),
        migrations.AddField(
            model_name='criticreview',
            name='summary_en',
            field=models.TextField(blank=True, help_text='Optional short quote or summary from the review', null=True, verbose_name='Summary Quote'),
        ),
        migrations.AddField(
            model_name='flag',
            name='description_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='flag',
            name='description_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='game',
            name='adjustment_guide_ar',
            field=models.TextField(blank=True, help_text='Instructions or links on how to adjust settings/mods for Halal/Mashbouh games.', null=True, verbose_name='Adjustment Guide'),
        ),
        migrations.AddField(
            model_name='game',
            name='adjustment_guide_en',
            field=models.TextField(blank=True, help_text='Instructions or links on how to adjust settings/mods for Halal/Mashbouh games.', null=True, verbose_name='Adjustment Guide'),
        ),
        migrations.AddField(
            model_name='game',
            name='aqidah_details_ar',
            field=models.TextField(blank=True, help_text='Specific examples related to Aqidah concerns (magic, deities, ideologies etc).', null=True, verbose_name='Aqidah Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='aqidah_details_en',
            field=models.TextField(blank=True, help_text='Specific examples related to Aqidah concerns (magic, deities, ideologies etc).', null=True, verbose_name='Aqidah Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='aqidah_reason_ar',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Aqidah severity rating.', null=True, verbose_name='Aqidah Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='aqidah_reason_en',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Aqidah severity rating.', null=True, verbose_name='Aqidah Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='audio_music_details_ar',
            field=models.TextField(blank=True, help_text='Details about background music, lyrics, ability to mute.', null=True, verbose_name='Audio/Music Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='audio_music_details_en',
            field=models.TextField(blank=True, help_text='Details about background music, lyrics, ability to mute.', null=True, verbose_name='Audio/Music Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='audio_music_reason_ar',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Audio/Music severity rating.', null=True, verbose_name='Audio/Music Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='audio_music_reason_en',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Audio/Music severity rating.', null=True, verbose_name='Audio/Music Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='immorality_details_ar',
            field=models.TextField(blank=True, help_text="Examples of 'Awrah, suggestive themes, promotion of impermissible relationships, bad language/conduct.", null=True, verbose_name='Immorality Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='immorality_details_en',
            field=models.TextField(blank=True, help_text="Examples of 'Awrah, suggestive themes, promotion of impermissible relationships, bad language/conduct.", null=True, verbose_name='Immorality Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='immorality_reason_ar',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Immorality severity rating.', null=True, verbose_name='Immorality Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='immorality_reason_en',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Immorality severity rating.', null=True, verbose_name='Immorality Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_conduct_details_ar',
            field=models.TextField(blank=True, help_text='Risks related to online chat, community toxicity, moderation.', null=True, verbose_name='Online Conduct Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_conduct_details_en',
            field=models.TextField(blank=True, help_text='Risks related to online chat, community toxicity, moderation.', null=True, verbose_name='Online Conduct Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_conduct_reason_ar',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Online Conduct severity rating.', null=True, verbose_name='Online Conduct Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='online_conduct_reason_en',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Online Conduct severity rating.', null=True, verbose_name='Online Conduct Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='rationale_ar',
            field=models.TextField(blank=True, help_text='General rationale summary (optional).', null=True, verbose_name='General Rationale'),
        ),
        migrations.AddField(
            model_name='game',
            name='rationale_en',
            field=models.TextField(blank=True, help_text='General rationale summary (optional).', null=True, verbose_name='General Rationale'),
        ),
        migrations.AddField(
            model_name='game',
            name='substances_gambling_details_ar',
            field=models.TextField(blank=True, help_text='Examples of substance use/promotion, gambling mechanics.', null=True, verbose_name='Substances/Gambling Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='substances_gambling_details_en',
            field=models.TextField(blank=True, help_text='Examples of substance use/promotion, gambling mechanics.', null=True, verbose_name='Substances/Gambling Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='substances_gambling_reason_ar',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Substances/Gambling severity rating.', null=True, verbose_name='Substances/Gambling Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='substances_gambling_reason_en',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Substances/Gambling severity rating.', null=True, verbose_name='Substances/Gambling Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='summary_ar',
            field=models.TextField(blank=True, help_text='Short description shown in lists.', null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='game',
            name='summary_en',
            field=models.TextField(blank=True, help_text='Short description shown in lists.', null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_addiction_details_ar',
            field=models.TextField(blank=True, help_text='Notes on addictive mechanics, time investment required, potential for neglecting duties.', null=True, verbose_name='Time/Addiction Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_addiction_details_en',
            field=models.TextField(blank=True, help_text='Notes on addictive mechanics, time investment required, potential for neglecting duties.', null=True, verbose_name='Time/Addiction Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_addiction_reason_ar',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Time/Addiction severity rating.', null=True, verbose_name='Time/Addiction Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='time_addiction_reason_en',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Time/Addiction severity rating.', null=True, verbose_name='Time/Addiction Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='game',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='game',
            name='violence_details_ar',
            field=models.TextField(blank=True, help_text='Specific examples of violence, gore, context.', null=True, verbose_name='Violence Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='violence_details_en',
            field=models.TextField(blank=True, help_text='Specific examples of violence, gore, context.', null=True, verbose_name='Violence Details'),
        ),
        migrations.AddField(
            model_name='game',
            name='violence_reason_ar',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Violence severity rating.', null=True, verbose_name='Violence Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='violence_reason_en',
            field=models.TextField(blank=True, help_text='Reasoning or reference for the Violence severity rating.', null=True, verbose_name='Violence Reason'),
        ),
        migrations.AddField(
            model_name='ratingtier',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ratingtier',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ratingtier',
            name='display_name_ar',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='ratingtier',
            name='display_name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Display Name'),
        ),
    ]
