# Generated by Django 5.1.7 on 2025-04-16 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_alter_flag_options_alter_game_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flag',
            options={'ordering': ['description'], 'verbose_name': 'Content Descriptor', 'verbose_name_plural': 'Content Descriptors'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='rationale',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rationale_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rationale_en',
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, help_text='Game overview description and overall rating reasoning (used in lists and detail view).', verbose_name='Summary & Rating Rationale'),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary_ar',
            field=models.TextField(blank=True, help_text='Game overview description and overall rating reasoning (used in lists and detail view).', null=True, verbose_name='Summary & Rating Rationale'),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary_en',
            field=models.TextField(blank=True, help_text='Game overview description and overall rating reasoning (used in lists and detail view).', null=True, verbose_name='Summary & Rating Rationale'),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('NEW_DESCRIPTOR', 'Suggest New Descriptor'), ('CHANGE_SEVERITY', 'Suggest Severity Change'), ('OTHER', 'Other Feedback/Correction')], max_length=20, verbose_name='Suggestion Type')),
                ('current_severity', models.CharField(blank=True, choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], max_length=1, verbose_name='Current Severity (auto-filled)')),
                ('suggested_severity', models.CharField(blank=True, choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], max_length=1, null=True, verbose_name='Suggested Severity (if applicable)')),
                ('suggested_descriptor_name', models.CharField(blank=True, max_length=150, verbose_name='Suggested Descriptor Name (if new)')),
                ('suggested_descriptor_icon', models.CharField(blank=True, max_length=100, verbose_name='Suggested Icon (optional)')),
                ('justification', models.TextField(help_text='Please provide details and reasons for your suggestion.', verbose_name='Justification / Details')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('IMPLEMENTED', 'Implemented'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15, verbose_name='Moderation Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('existing_descriptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='severity_suggestions', to='ratings.flag', verbose_name='Existing Descriptor (if applicable)')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='ratings.game', verbose_name='Game (Optional)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='User (Optional)')),
            ],
            options={
                'verbose_name': 'User Suggestion',
                'verbose_name_plural': 'User Suggestions',
                'ordering': ['-created_date'],
            },
        ),
        migrations.DeleteModel(
            name='UserContribution',
        ),
    ]
