# Generated by Django 5.1.7 on 2025-04-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0013_criticreview_summary_ar_criticreview_summary_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='available_quest',
            field=models.BooleanField(default=False, verbose_name='Available on Meta Quest'),
        ),
    ]
