# Generated by Django 5.1.7 on 2025-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0014_game_boycott_reason_game_is_boycotted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='assuming_divinity_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='A3. Assuming Divinity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='crime_violence_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='C4. Crime/Violence'),
        ),
        migrations.AlterField(
            model_name='game',
            name='despair_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='D2. Despair'),
        ),
        migrations.AlterField(
            model_name='game',
            name='deviant_ideologies_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='A5. Deviant Ideologies'),
        ),
        migrations.AlterField(
            model_name='game',
            name='disdain_arrogance_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='C1. Disdain/Arrogance'),
        ),
        migrations.AlterField(
            model_name='game',
            name='distorting_islam_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='A1. Distorting Islam'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gambling_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='B1. Gambling'),
        ),
        migrations.AlterField(
            model_name='game',
            name='horror_fear_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='D1. Horror/Fear'),
        ),
        migrations.AlterField(
            model_name='game',
            name='indecency_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='B3. Indecency'),
        ),
        migrations.AlterField(
            model_name='game',
            name='intoxicants_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='C3. Intoxicants'),
        ),
        migrations.AlterField(
            model_name='game',
            name='lying_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='B2. Lying'),
        ),
        migrations.AlterField(
            model_name='game',
            name='magic_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='C2. Magic'),
        ),
        migrations.AlterField(
            model_name='game',
            name='music_instruments_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='B4. Music/Instruments'),
        ),
        migrations.AlterField(
            model_name='game',
            name='online_interactions_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='D4. Online Interactions'),
        ),
        migrations.AlterField(
            model_name='game',
            name='profanity_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='C5. Profanity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='promoting_kufr_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='A2. Promoting Kufr/Shirk'),
        ),
        migrations.AlterField(
            model_name='game',
            name='spending_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='D3. Spending'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tampering_ghaib_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='A4. Tampering Ghaib'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_waste_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='B5. Time Waste'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_content_severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Mild'), ('M', 'Moderate'), ('S', 'Severe')], default='N', max_length=1, verbose_name='D5. User Content'),
        ),
    ]
