# Generated by Django 5.1.7 on 2025-04-19 10:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0015_alter_game_assuming_divinity_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boycottedentity',
            name='reason_ar',
            field=models.TextField(blank=True, help_text='Optional: Briefly explain the reason.', null=True, verbose_name='Reason for Boycott'),
        ),
        migrations.AddField(
            model_name='boycottedentity',
            name='reason_en',
            field=models.TextField(blank=True, help_text='Optional: Briefly explain the reason.', null=True, verbose_name='Reason for Boycott'),
        ),
        migrations.AddField(
            model_name='game',
            name='alternative_games',
            field=models.ManyToManyField(blank=True, help_text='Suggest permissible alternatives, especially if this game is rated Haram or Kufr/Shirk.', related_name='suggested_as_alternative_for', to='ratings.game', verbose_name='Suggested Alternatives'),
        ),
        migrations.AddField(
            model_name='game',
            name='boycott_reason_ar',
            field=models.TextField(blank=True, help_text='Reason for the game-specific boycott (if applicable).', null=True, verbose_name='Game Boycott Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='boycott_reason_en',
            field=models.TextField(blank=True, help_text='Reason for the game-specific boycott (if applicable).', null=True, verbose_name='Game Boycott Reason'),
        ),
        migrations.AddField(
            model_name='game',
            name='guide_for_parents',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Specific advice and discussion points for parents regarding this game.', null=True, verbose_name='Guide for Parents'),
        ),
        migrations.AddField(
            model_name='game',
            name='guide_for_parents_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Specific advice and discussion points for parents regarding this game.', null=True, verbose_name='Guide for Parents'),
        ),
        migrations.AddField(
            model_name='game',
            name='guide_for_parents_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Specific advice and discussion points for parents regarding this game.', null=True, verbose_name='Guide for Parents'),
        ),
        migrations.AddField(
            model_name='game',
            name='iarc_rating',
            field=models.CharField(blank=True, choices=[('', 'Not Rated'), ('3+', 'IARC 3+'), ('7+', 'IARC 7+'), ('12+', 'IARC 12+'), ('16+', 'IARC 16+'), ('18+', 'IARC 18+')], default='', help_text='Official International Age Rating Coalition rating, if available.', max_length=5, verbose_name='IARC Rating'),
        ),
    ]
