# Generated by Django 5.1.7 on 2025-04-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0016_boycottedentity_reason_ar_boycottedentity_reason_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='alternative_games',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guide_for_parents',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guide_for_parents_ar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guide_for_parents_en',
        ),
    ]
