BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB 

BBBBB BBBBB X  gettext(u'IGS Rating Details') BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBB
                
                XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXX gettext(u'%(game.title)s Cover') SSSSSSSSSSSSSS SSSSSXX
            BBBB
                 
                XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX gettext(u'No Image') XXXXXXXXXXXXX
            BBBBB
        XXXXXX
         
         BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBB
             BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Available On:') XXXXX
                    
                    BB BBBBBBBBBBBBBBBXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Steam') XXXXBBBBB
                    BB BBBBBBBBBBBBBBXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Epic Games') XXXXBBBBB
                    BB BBBBBBBBBBBBBXX XXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'GOG') XXXXBBBBB
                     BB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Other') XXXXBBBBB
                XXXXXX
            BBBBB
         BBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXX XXXXXX
             
             BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB
                 XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
             BBBB BBBBBBBBBBBBBB
                 
             BBBBB
             BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBB X BBBBB
              BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB
                 XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
             BBBB BBBBBBBBBBBBBB
                 
             BBBBB
            BB BBBBBBBBBBBBBBBBB XFFFFFFFFXBBBBB
        XXXX
		
        
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Overall IGS Rating:') XXXXXXX
				 XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
					   XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXBBBBXXXXBBBBBXXX
					 XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
					 	
						
						
						  BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB

						   gettext(u'Haram') 
						   gettext(u'Mashbouh') 
						   gettext(u'Halal') 
						   gettext(u'Kufr') 
						  
						
						 XXXXX XXXXXXXXXXXXXXXXXXXXX
							
							BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBB
							BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
							BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBB
							BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBB
							BBBB 
							BBBBB
						 XXXXXXX
						 
						 
					 
				 XXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Requires Adjustment') XXXXXXX
            BBBBB
        XXXXXX

         
        BB BBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXX
             XXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Content Flags:') XXXXXXX
            BBB BBBB BB BBBBBBBBBBBBBB
                
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            BBBBBB
        XXXXXX
        BBBBB
         
        BB BBBBBBBBBBBB
            XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBBB

        
        BB BBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
             
             XXXX gettext(u'Adjustment Guide') XXXXX
             XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                FFFFFFFFFF
             XXXXXX
        XXXXXX
        BBBBB

    XXXXXX
XXXXXX


BB BBBBBBBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Critic Reviews') XXXXX
    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXX
        BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                BB BBBBBBBBBBBBBB
                XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XFFFFFFFFFFFFFFFFX
                XXXXXXXXXXXXX
                BBBBB
                XX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
                     gettext(u'Read Full Review')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXXX
        XXXXXX
        BBBBBB
    XXXXXX
XXXXXX
BBBBB



XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Islamic Guidance Breakdown') XXXXX

    
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX X XX XXXX
          XXXXX XXXXXXXXX XXXXXXXXXX XXXX X X XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X X XXXXX XXXXX XXXXXXXXXXXXXX X X X X XXXXXX XXX X X X X X X X X X X X XXXXXX
      XXXXXX
      
      XXXXXXXX gettext(u'Spoiler Warning:') XXXXXXXXX  gettext(u"Details below may contain plot spoilers. Click 'Show/Hide Details' where available to reveal.") 
    XXXXXX
    BBBBB

    
    
    BB BBBBBBBBBBBBBBBBBBBB BB BBB BB BBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Aqidah & Ideology') XXXXXXX
            
            XXXXX XXXXXXXXXXXXXXXXXXXXXX FFFFFX XXXXXXX gettext(u'Severity: %(game.aqidah_severity_display)s') SSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXXXXXXX
        XXXXXX
        XXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX BBBB XXXXXXXX BBBBBX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFBBBBXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX gettext(u'No specific details provided.') XXXXBBBBB
                BB BBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Reasoning/Reference:') XXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXBBBBB
            XXXXXX
        XXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Show/Hide Details') XXXXXXXXXXXXXXXBBBBB
    XXXXXX
    BBBBB

    
    BB BBBBBBBBBBBBBBBBBBBBBB BB BBB BB BBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Violence & Aggression') XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX FFFFFX XXXXXXX gettext(u'Severity: %(game.violence_severity_display)s') SSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXXXXXXX
        XXXXXX
        XXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX BBBB XXXXXXXX BBBBBX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFBBBBXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX gettext(u'No specific details provided.') XXXXBBBBB
                BB BBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Reasoning/Reference:') XXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXBBBBB
            XXXXXX
        XXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Show/Hide Details') XXXXXXXXXXXXXXXBBBBB
    XXXXXX
    BBBBB

    
    BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBB BB BBBBBBBBBBBBBBBBBBBBBBB
     XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Immorality & Indecency') XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX FFFFFX XXXXXXX gettext(u'Severity: %(game.immorality_severity_display)s') SSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXXXXXXX
        XXXXXX
         XXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX BBBB XXXXXXXX BBBBBX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 BB BBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFBBBBXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX gettext(u'No specific details provided.') XXXXBBBBB
                 BB BBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Reasoning/Reference:') XXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXBBBBB
            XXXXXX
        XXXXXX
         BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Show/Hide Details') XXXXXXXXXXXXXXXBBBBB
    XXXXXX
    BBBBB

    
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
     XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Haram Substances & Gambling') XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX FFFFFX XXXXXXX gettext(u'Severity: %(game.substances_gambling_severity_display)s') SSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXXXXXXX
        XXXXXX
         XXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX BBBB XXXXXXXX BBBBBX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFBBBBXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX gettext(u'No specific details provided.') XXXXBBBBB
                 BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Reasoning/Reference:') XXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXBBBBB
            XXXXXX
        XXXXXX
         BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Show/Hide Details') XXXXXXXXXXXXXXXBBBBB
    XXXXXX
    BBBBB

    
    BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBB BB BBBBBBBBBBBBBBBBBBBBBBBB
     XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Audio & Music') XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX FFFFFX XXXXXXX gettext(u'Severity: %(game.audio_music_severity_display)s') SSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXXXXXXX
        XXXXXX
         XXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX BBBB XXXXXXXX BBBBBX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 BB BBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFBBBBXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX gettext(u'No specific details provided.') XXXXBBBBB
                 BB BBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Reasoning/Reference:') XXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXBBBBB
            XXXXXX
        XXXXXX
         BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Show/Hide Details') XXXXXXXXXXXXXXXBBBBB
    XXXXXX
    BBBBB

    
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
     XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Time Commitment & Addiction Potential') XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX FFFFFX XXXXXXX gettext(u'Severity: %(game.time_addiction_severity_display)s') SSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXXXXXXX
        XXXXXX
         XXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BBBB XXXXXXXX BBBBBX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 BB BBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFBBBBXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX gettext(u'No specific details provided.') XXXXBBBBB
                 BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Reasoning/Reference:') XXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXBBBBB
            XXXXXX
        XXXXXX
         BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Show/Hide Details') XXXXXXXXXXXXXXXBBBBB
    XXXXXX
    BBBBB

    
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
     XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Online Conduct & Interaction') XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX FFFFFX XXXXXXX gettext(u'Severity: %(game.online_conduct_severity_display)s') SSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXXXXXXX
        XXXXXX
         XXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX BBBB XXXXXXXX BBBBBX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 BB BBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFBBBBXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX gettext(u'No specific details provided.') XXXXBBBBB
                 BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Reasoning/Reference:') XXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXBBBBB
            XXXXXX
        XXXXXX
         BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Show/Hide Details') XXXXXXXXXXXXXXXBBBBB
    XXXXXX
    BBBBB

    
    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBB BB BBB BBB BBB BBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBB BB BBB BBB BBB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBB BBB BBB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBB BBB BBB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBB BBB BBB BBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBB BBB BBB BBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBB BBB BBB BBBBBBBBBB
            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'No significant Islamic concerns noted in the assessed categories.') XXXX
        BBBBB
    BBBBBBB

XXXXXX



XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXX gettext(u'← Back to Game Ratings') XXXX

BBBBBBBB