BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB 

BBBBB BBBBBBBBBBBBB 

BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX 
     
     XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX
        
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Title/Dev...') X XXXXXXXXXXXX gettext(u'Search') X XXXXXXXX XXXXXXXFFFFFFFFFFXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Search') XXXXXXXXX
     XXXXXXX
    
  XXXXXX

   BB BBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
            FFFF 
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX gettext(u'Clear Filter') XXXX
        XXXXXX
   BBBBB

  
  XXXXX XXXXXXXXXXXX XXXXXXXXBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
        
        BB BBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        BBBBB

        
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Rating Tier') XXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXX BB BBB BBBBBBBBBBBBB BB BBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBX gettext(u'All Tiers') XXXXXXXXX
            BBB BBBB BB BBBBBBBBB
              XXXXXXX XXXXXXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBXXXXXXXXBBBBBX
                   
              XXXXXXXXX
            BBBBBB
          XXXXXXXXX
        XXXXXX

        
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
           XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Adjustment') XXXXXXXX
           XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
               XXXXXXX XXXXXXXX BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Any') XXXXXXXXX
               XXXXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBX gettext(u'Required') XXXXXXXXX
               XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBX gettext(u'Not Required') XXXXXXXXX
           XXXXXXXXX
        XXXXXX

        
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Sort By') XXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Date Added (Newest)') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Date Added (Oldest)') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX BB BBBBBBB BB BBBBBBBXXXXXXXXBBBBBX gettext(u'Title (A-Z)') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXX BB BBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX gettext(u'Title (Z-A)') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXX BB BBBBBBB BB BBBBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Release Date (Newest)') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBB BB BBBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Release Date (Oldest)') XXXXXXXXX
          XXXXXXXXX
        XXXXXX

        
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Apply Filters') XXXXXXXXX
        XXXXXX

      XXXXXX
    XXXXXX
  XXXXXXX
  

  
  BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB

   gettext(u'Haram') 
   gettext(u'Mashbouh') 
   gettext(u'Halal') 
   gettext(u'Kufr') 
  

  XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX
    BBB BBBB BB BBBBBBBBBB
    XXXX XXXXXXXXXXXX
         
         BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    BBBBB
      XX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBB BB BBBBBBBBBBBBB BB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
            
            BBB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
            
             gettext(u'No games found matching your criteria. <a href="%(all_games_url)s" class="link-secondary">View all games?</a>') SS SSSSS SSSSS SSSSSSSS SSSS SSSSSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSS SSS SSSSSSSSSS
        BBBB
             gettext(u'No games rated yet.') 
        BBBBB
      XXXX
    BBBBBB
  XXXXXX

  
    XXXX XXXXXXXXXXXX gettext(u'Game list navigation') X XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXBBB BBBB BBBBB BB BBBBBBBBBBBBBBBBBBB BBB BB BBBBBBXXBBBBBBBBBBBXX gettext(u'« First') XXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXBBB BBBB BBBBB BB BBBBBBBBBBBBBBBBBBB BBB BB BBBBBBXXBBBBBBBBBBBXX gettext(u'Previous') XXXX
          XXXXX
        BBBB
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'« First') XXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Previous') XXXXXXXXXXXX
        BBBBB

        XXX XXXXXXXXXXXXXXXX XXXXXXXXXX
            
            XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Page %(games_page.number)s of %(games_page.paginator.num_pages)s') SSSS SSSSSSSSSSSSSSSSSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXXXXX
        XXXXX

        BB BBBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXBBB BBBB BBBBB BB BBBBBBBBBBBBBBBBBBB BBB BB BBBBBBXXBBBBBBBBBBBXX gettext(u'Next') XXXX
          XXXXX
           XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXBBB BBBB BBBBB BB BBBBBBBBBBBBBBBBBBB BBB BB BBBBBBXXBBBBBBBBBBBXX gettext(u'Last »') XXXX
          XXXXX
        BBBB
           XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Next') XXXXXXXXXXXX
           XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Last »') XXXXXXXXXXXX
        BBBBB
      XXXXX
    XXXXXX
  

BBBBBBBB