BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB 

BBBBB BBBBB gettext(u'MGC Blog') BBBBBBBB

BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'Blog') XXXXX
    
    XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXX
        
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Articles...') X XXXXXXXXXXXX gettext(u'Search Articles') X XXXXXXXX XXXXXXXFFFFFFFFFFXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Search') XXXXXXXXX
    XXXXXXX
    
  XXXXXX

  BB BBBBBBBBBBBB
      
      XX XXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Showing results for: <strong>"%(search_query)s"</strong>') SSSSSSS SSSSSSS SSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXX
  BBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBB BBBBBBB BB BBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX
             XX XXXXXXXXXXXX 
          XXXXX
          XX XXXXXXXXXXXXXXXXXXXXX
              
               gettext(u'Published on %(article.published_date|date:"F j, Y")s') SSSSSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS SSSS
              BB BBBBBBBBBBBBBBBBBBB  gettext(u'by %(article.author_name)s') SS SSSSSSSSSSSSSSSSSSSSSSSBBBBB
          XXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFFFF 
          XXXX
          
          XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Read More →') XXXX
      XXXXXX
    BBBBB
      XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
         BB BBBBBBBBBBBB
            gettext(u'No articles found matching your search criteria.') 
         BBBB
            gettext(u'No articles published yet.') 
         BBBBB
      XXXX
    BBBBBB
  XXXXXX
BBBBBBBB