BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB 

BBBBB BBBBB X  gettext(u'IEGS Article') BBBBBBBB

BBBBB BBBBBBB
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX

      BB BBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
          
          XXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXX gettext(u'%(article.title)s Header Image') SSSSSSSSSSSSSSSSS SSSSSS SSSSSX XXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXX
      BBBBB

      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          
           gettext(u'Published:')  FFFFFFF FF FF
          BB BBBBBBBBBBBBBBBBBBB X  gettext(u'By:')  BBBBB
      XXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          FFFFFFFFFF 
      XXXXXX

      
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXX gettext(u'← Back to Articles') XXXX
  XXXXXXXXXX
BBBBBBBB