BBBB BBBBBB
BBBB BBBB
XXXXXXXXX XXXXX

XXXXX XXXXXXFFFFFFFFFFFFX BB BBBBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXXXBBBBBX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXXBBBBB BBBBB gettext(u'IGS Ratings') BBBBBBBB X  gettext(u'IGS') XXXXXXXX

  
  
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

  
  BB BBBBBBBBBBBBBBBBBBBBB BB BBBB
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  BBBBB
  

  XXXX XXXXXX XXXXX XXXXXXXX XXXX XXX XXXX XXX XXXXX XXXXXXXX XXXX XXXXXXX XX XXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

  XXXX XXXXXXXX XXXXXXX XXXX XXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX

  XXXX XXXXXX XXX XXXXX XXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX

  
  XXXXX XXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX

XXXXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX

  
  BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

  XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
         XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBXX  gettext(u'IGS')  XXXX
         XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXX
         XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                
                XXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX gettext(u'Games') XXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Blog') XXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBBBXX gettext(u'Glossary') XXXX
                XXXXX

                
                XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXBBBBBX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Account') 
                  XXXX
                  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Salaam, %(user.username)s!') SSSSSSS SSSSSSSSSSSSSSSSSSXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Change Password') XXXXXXXXX
                         BB BBBBBBBBBBBBB
                           XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                           XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Site Admin') XXXXXXXXX
                         BBBBB
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX gettext(u'Logout') XXXX
                        XXXXX
                    BBBB
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXXXXXXXX gettext(u'Login') XXXXXXXXX
						XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBXX gettext(u'Sign Up') XXXXXXXXX
						BB BBBBBBBBBBBBB
						   XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Site Admin') XXXXXXXXX
						BBBBB
                    BBBBB
                  XXXXX
                XXXXX

                
                XXX XXXXXXXXXXXXXXXXX
                    
                    XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                    XXXXXXXXX

                    
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                        BBBBBBBBBB
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                        BBBBBBBBBB
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXX
                XXXXX
                

				
				XXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Toggle light/dark theme') XX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXX
            XXXXX
         XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXX

  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
    BBBBB BBBBBBB
    BBBBBBBB
  XXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
       
       BBB BBB BB BBBBBBBBBBBB
       XX XXXXXXXXXXXXXXXXXXXX
         
          gettext(u'Islamic Gaming Standard © %(current_year)s.') SSSSSSS SSSSSS SSSSSSSS S SSSSSSSSSSSSSSSSS
       XXXX
    XXXXXX
 XXXXXXXXX

  XXXX XXXXXXXXX XXXXXX XX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

   BBBBB BBBBBBBB
   BBBBBBBB

   XXXXXXXX
      XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
      XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XX XXXXXXXX XX XXXXX XXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXX X
          XX XXXXXX XXX XXXXXXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XX XXXX XXXX XXXX XXX XXXXX XXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
          X XXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XX XXXX XXX XXXX XXX XXXX XXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
          X
      X

      XX XXXXXXXXXX XXXXX XXXXX XX XXXXXXXXXX XX XXXXXXX
      XX XXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXX
      X XXXX XX XXXXXXXXXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXX XX XXXXXXX XX XXXX XX XXXX XXXXXXX XX XXX XX XXXXXXX XXX
      X XXXX X
          XXXXXXXXXXXXXXXXXXX XX XXXXXXX XX XXXX XXXXXXXXX
      X

      XX XXXXXX XXXXX XXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
          XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXX
          XXXXXXXXXXXXXXXXXXXXX
      XXX

      XX XXXXXX XXX XXXXXXX XX XX XXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
          XX XXXX XXXXXX XX XX XXXXXXXX XXXXXX XXX XXXX XXX XXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
              XXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXXX
          X
      XXX
	  
	      XX XXX XXXXXX XXXXXXXX XXXXXX XXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXX XXXXXXXX XXXXX XXXXXX XXXX XXXXXXXX XXX XX XXXXXXX XXXX XXXX XXXX
    XXXXX XXXXXXXXXXXXXXX X XXX
    XX XXXX XXX XXXXXXXX XXXX XXXX

    XX XXX XXXXX XX XXX XXXXX XX XXXXXXX XX XXX XXXXXXX XXXX XXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXX XXXXXXX XXXXXX XXXXX
    XX XXXXXXXXXXXXXXXX XXX XXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XX XXXX XX XX XXXXXXX XX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Switch to English') XX
    X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XX XXXX XXX XX XXXXXXX XX XXXXXXX XXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Switch to Arabic') XX
    X

    XX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXX XXXXXXXXXXXXXX X XXX
        XXX XXXXXXXXXXXX X XXX

        XX XXXXXXXXXXXXXXXX XXX XXXXX X
            XXXXXXXXXXXXXX X XXXXX
            XXXXXXXXXXXX X XXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXX X XXXXX
            XXXXXXXXXXXX X XXXXXXXXXXXXXXX
        X

        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX X
            XX XXXXXX XXX XXXXXX XXXXX XXXX XXXXXX XXXXXXXXXX XX XXXXXX XXXX XXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XX XXXXXXXXXXX X
                  XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
             X
            XXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXX XX XXX XXXXX XXXXXXX
        X
    XXX
    XX XXX XXXX XXXXXXXX XXXXXX XXXXXX XXX

  XXXXXXXXX

XXXXXXX
XXXXXXX