BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'IGS - Islamic Gaming Standard') BBBBBBBB

BBBBB BBBBBBB


  

  
  BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB

   gettext(u'Haram') 
   gettext(u'Mashbouh') 
   gettext(u'Halal') 
   gettext(u'Kufr') 
  


  
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Islamic Gaming Standard') XXXXX
      XX XXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Navigating video games according to the Quran & Sunnah as understood by As-Salaf. Find ratings and guidance.') 
      XXXX
      XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXX gettext(u'Browse Game Ratings') XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX gettext(u'Read Articles') XXXX
      XXXXXX
  XXXXXX

  
  XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'What is IGS?') XXXXX
        XX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
             gettext(u'The Islamic Gaming Standard (IGS) provides ratings and detailed guidance for video games based on the principles of the Quran and the Sunnah, following the understanding of the Salaf-us-Salih (Pious Predecessors). Our goal is to help Muslims make informed decisions about the games they play.') SSS SSSSSSS SSSSSS SSSSSSSS SSSSS SSSSSSSS SSSSSSS SSS SSSSSSSS SSSSSSSS SSS SSSSS SSSSS SSSSS SS SSS SSSSSSSSSS SS SSS SSSSS SSS SSS SSSSSSS SSSSSSSSS SSS SSSSSSSSSSSSS SS SSS SSSSSSSSSSSSSS SSSSSS SSSSSSSSSSSSSS SSS SSSS SS SS SSSS SSSSSSS SSSS SSSSSSSS SSSSSSSSS SSSSS SSS SSSSS SSSS SSSSS
        XXXX
        
        
    XXXXXX
  XXXXXXXXXX

  
  XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX gettext(u'Featured Halal Games') XXXXX
        XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBB
                BBB BBBB BB BBBBBBBBBBBBBBB
                   XXXX XXXXXXXXXXXX
                       
                       BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
                   XXXXXX
                BBBBBB
            BBBB
               XX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'No Halal games featured yet.') XXXX
            BBBBB
       XXXXXX
       BB BBBBBBBBBBBBBBB
       XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'View All Halal Rated Games') XXXX
        XXXXXX
        BBBBB
    XXXXXX
  XXXXXXXXXX

  
  XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX gettext(u'Recent Articles & Insights') XXXXX
        BB BBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              BBB BBBBBBB BB BBBBBBBBBBBBBBB
                  XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXFFFFFFF FFXXXXXXXX 
                      XXXXXX
                      XX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFXXXX
                      BB BBBBBBBBBBBBBBBBBBB
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'By %(article.author_name)s') SS SSSSSSSSSSSSSSSSSSSSSSSXXXXXXXX
                      BBBBB
                  XXXX
               BBBBBB
            XXXXXX
             XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'View All Articles') XXXX
              XXXXXX
        BBBB
            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'No articles published yet.') XXXX
        BBBBB
    XXXXXX
  XXXXXXXXXX

BBBBBBBB